"""
Commercial Conversion Workflow Package (Phase 10.0)
"""

from lib.commercial.models import (
    CommercialStage,
    WebsitePipelineStage,
    OutcomeProvenance,
    InterestLevel,
    PreviewStatus,
    ProposalState,
    ProposalStatus,
    ProposalPackage,
    LostReason,
    NextActionType,
    CommercialEventType,
    CommercialNotes,
    FollowUpRecord,
    PreviewRecord,
    ProposalRecord,
    ProposalDocument,
    CommercialEvent,
    AUTO_CALL,
    AUTO_DM,
    AUTO_EMAIL,
    AUTO_FOLLOWUP,
    AUTO_CALLBACK,
    AUTO_PROPOSAL,
    AUTO_SEND_PROPOSAL,
    AUTO_EMAIL_PROPOSAL,
    AUTO_PAYMENT_REQUEST,
    AUTO_CONTRACT,
    AUTO_CONTINUATION,
)
from lib.commercial.commercial_pipeline_manager import CommercialPipelineManager
from lib.commercial.proposal_manager import ProposalManager

__all__ = [
    "CommercialStage",
    "WebsitePipelineStage",
    "OutcomeProvenance",
    "InterestLevel",
    "PreviewStatus",
    "ProposalState",
    "ProposalStatus",
    "ProposalPackage",
    "LostReason",
    "NextActionType",
    "CommercialEventType",
    "CommercialNotes",
    "FollowUpRecord",
    "PreviewRecord",
    "ProposalRecord",
    "ProposalDocument",
    "CommercialEvent",
    "CommercialPipelineManager",
    "ProposalManager",
    "AUTO_CALL",
    "AUTO_DM",
    "AUTO_EMAIL",
    "AUTO_FOLLOWUP",
    "AUTO_CALLBACK",
    "AUTO_PROPOSAL",
    "AUTO_SEND_PROPOSAL",
    "AUTO_EMAIL_PROPOSAL",
    "AUTO_PAYMENT_REQUEST",
    "AUTO_CONTRACT",
    "AUTO_CONTINUATION",
]
